# Generated by Django 5.1.1 on 2024-09-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='product name')),
                ('can be image or text', models.CharField(max_length=500, unique=True, verbose_name='product typr')),
                ('price', models.IntegerField(verbose_name='price of products')),
            ],
        ),
    ]
