# Generated by Django 5.1.1 on 2024-09-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testingapp', '0002_remove_products_can_be_image_or_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='title',
            field=models.CharField(max_length=500, null=True, verbose_name='product type can be image or text'),
        ),
    ]
