# Generated by Django 5.1.1 on 2024-09-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testingapp', '0003_products_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='apple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='product name')),
                ('title', models.CharField(max_length=500, null=True, verbose_name='product type can be image or text')),
                ('price', models.IntegerField(verbose_name='price of products')),
            ],
        ),
    ]
