# Generated by Django 5.1.1 on 2024-10-10 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testingapp', '0006_alter_phones_is_chart_alter_phones_pro_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phones',
            name='verification_code',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='please do not add this for it will add authomaticaly'),
        ),
        migrations.AlterField(
            model_name='phones',
            name='visit',
            field=models.IntegerField(blank=True, null=True, verbose_name='number of times visited pleas ignord this for it autumatically add it self'),
        ),
    ]
