# Generated by Django 5.1.1 on 2024-10-10 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testingapp', '0007_alter_phones_verification_code_alter_phones_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phones',
            name='verification_code',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='please do not add this for it will add authomaticaly'),
        ),
    ]
