# Generated by Django 5.1.1 on 2024-10-16 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testingapp', '0008_alter_phones_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='phones',
            name='currency',
            field=models.CharField(choices=[('NGN', 'NGN'), ('USD', 'USD')], max_length=4, null=True),
        ),
    ]
