# Generated by Django 5.1.1 on 2024-11-01 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testingapp', '0010_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='Ram',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='cart_id',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='cellular_tech',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='color',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='connectivity',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='image',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='memory',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='operating_systerm',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='post_date',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='price',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='pro_request',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='resolution',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='screen',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='verification_code',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='visit',
        ),
    ]
