# Generated by Django 5.1.1 on 2024-11-01 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testingapp', '0011_remove_cart_ram_remove_cart_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='ordered product image'),
        ),
    ]
